# -*- coding: utf-8 -*-
"""Lab05Aula07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTJiOOWnbUv5RBh55XnJRQMMU4Fbftkn
"""

import numpy as np

# Função Rastrigin (Função com múltiplos mínimos locais)
def rastrigin(x):
    return 10 * len(x) + sum(x**2 - 10 * np.cos(2 * np.pi * x))


def local_search_hill_climbing(solution, step_size=0.01, max_steps=20):
    """Mecanismo de Intensificação (Aprendizado Individual / Memética)"""

    current_sol = np.copy(solution)
    current_fit = rastrigin(current_sol)

    for _ in range(max_steps):
        # Gera um vizinho adicionando um pequeno ruído aleatório
        neighbor = current_sol + np.random.uniform(
            -step_size,
            step_size,
            size=len(solution)
        )

        # Calcula o fitness do vizinho
        neighbor_fit = rastrigin(neighbor)

        # Aceita o vizinho caso ele seja melhor
        if neighbor_fit < current_fit:
            current_sol = neighbor
            current_fit = neighbor_fit

    return current_sol, current_fit


# Teste da Busca Local Isolada
initial_solution = np.array([2.5, -3.1])

refined_solution, final_fit = local_search_hill_climbing(initial_solution)

print(
    f"[LAB 05] Solução Inicial: {initial_solution} | "
    f"Fitness: {rastrigin(initial_solution):.4f}"
)

print(
    f"[LAB 05] Solução Refinada: {refined_solution} | "
    f"Fitness: {final_fit:.4f}"
)


# Questões Técnicas — LAB 05
# 1 - Qual a diferença fundamental de conceito entre um Algoritmo Genético Puro e um Algoritmo Memético?
# 2 - Em termos de custo computacional, qual o impacto de executar a busca local sobre todos os indivíduos de uma população a cada geração?