# -*- coding: utf-8 -*-
"""Lab01Aula07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTJiOOWnbUv5RBh55XnJRQMMU4Fbftkn
"""

import numpy as np

# Problema da Mochila (Blindagem de Ativos)
weights = np.array([12, 2, 1, 4, 1])
values = np.array([4, 2, 1, 10, 2])
max_weight = 15

pop_size = 10
num_genes = len(weights)
generations = 10
mutation_rate = 0.1

# Inicialização da População
population = np.random.randint(0, 2, size=(pop_size, num_genes))


def calculate_fitness(ind):
    total_weight = np.sum(ind * weights)
    total_value = np.sum(ind * values)

    # Penalização dos indivíduos que ultrapassam o peso máximo
    if total_weight > max_weight:
        return 0
    else:
        return total_value


def tournament_selection(pop, fitnesses):
    # Seleciona dois indivíduos aleatórios
    idx1, idx2 = np.random.choice(len(pop), size=2, replace=False)

    # Retorna o indivíduo com maior fitness
    if fitnesses[idx1] >= fitnesses[idx2]:
        return pop[idx1].copy()
    else:
        return pop[idx2].copy()


def crossover(parent1, parent2):
    point = np.random.randint(1, num_genes)

    child1 = np.concatenate([parent1[:point], parent2[point:]])
    child2 = np.concatenate([parent2[:point], parent1[point:]])

    return child1, child2


def mutate(ind):
    for i in range(num_genes):
        if np.random.rand() < mutation_rate:
            ind[i] = 1 - ind[i]

    return ind


# Loop Evolutivo
for g in range(generations):
    fitnesses = np.array([calculate_fitness(ind) for ind in population])

    new_population = []

    for _ in range(pop_size // 2):
        p1 = tournament_selection(population, fitnesses)
        p2 = tournament_selection(population, fitnesses)

        c1, c2 = crossover(p1, p2)

        new_population.extend([
            mutate(c1),
            mutate(c2)
        ])

    population = np.array(new_population)

    # Melhor indivíduo da geração
    best_idx = np.argmax(fitnesses)
    best_ind = population[best_idx]

    print(
        f"Geração {g + 1}: "
        f"Melhor fitness = {fitnesses[best_idx]}"
    )


# Resultado final
fitnesses = np.array([calculate_fitness(ind) for ind in population])
best_idx = np.argmax(fitnesses)

best_ind = population[best_idx]
best_weight = np.sum(best_ind * weights)
best_value = np.sum(best_ind * values)

print("\n[LAB 02] Resultado final")
print("Melhor indivíduo:", best_ind)
print("Peso total:", best_weight)
print("Valor total:", best_value)
print("Fitness:", fitnesses[best_idx])